[package]
name = "clink"
version = "0.6.3"
authors = ["Serhiy Barhamon <bargamon@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.8.0"
linkify = "0.7.0"
url = "2.2.2"
rustop = "1.1.1"
rand = "0.8.4"
confy="0.4.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
dirs-next = "2.0.0"
toml = "0.5.8"
