[package]
name = "clink"
version = "0.6.2"
authors = ["Sergey Bargamon <sergey@bargamon.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = { git = "https://github.com/Lurk/copypasta.git", branch = "master"  }
linkify = "0.7.0"
url = "2.2.2"
rustop = "1.1.1"
rand = "0.8.4"
confy="0.4.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
dirs-next = "2.0.0"
toml = "0.5.8"