[package]
name = "clink"
version = "0.6.0"
authors = ["Sergey Bargamon <sergey@bargamon.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
linkify = "0.4.0"
url = "2.2.0"
rustop = "1.1.1"
rand = "0.8.3"
confy="0.4.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
dirs-next = "2.0.0"
toml = "0.5.8"