name: lint and test

on: [push, pull_request]

jobs:
  Test:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-16.04
            name: Linux
          - os: ubuntu-18.04
            name: Linux
          - os: ubuntu-20.04
            name: Linux
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable    
    - name: Dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install libxkbcommon-dev
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
